### ISSUE TITLE
Project Requirements Checklist

### ISSUE THREAD

**Issue by ChrisPitts** [ChrisPitts/Project-1#4]
Workflow Requirements
- [x] 3 user stories
- [ ] Wireframes

Technical Requirements
- [ ] 3 separate HTML pages
- [x] style.css in /css folder
- [ ] all html pages link to styles.css
- [ ] pages linked together by a tags
- [x] at least one img tag
- [x] form with at least 3 fields, two required
- [x] form submission with formspree (optional)
- [x] one page using a multi-column layout
- [x] bootstrap carousel (optional)
- [x] in github repository
- [ ] html validated with html validator with no errors

Deliverables
- [x] user stories
- [ ] collection of wireframes
- [x] src in github repo
- [x] at least 15 commits
- [x] hosted on github pages

readme.md
- [ ] your name
- [ ] overview/description of project
- [ ] details on how to use or functionality
- [ ] technologies used
- [ ] ideas for future improvement

**Comment by ChrisPitts** [comment]
Added user stories in https://github.com/ChrisPitts/Project-1/commit/669ffec2491d5aabca5d46b3d5d451cb7fa84003
